### ISSUE TITLE
FacDB 25v1

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#1334]
# FacDB Source Data Updates

Like most of our data products, source data must be updated in data library before FacDB is run. As there are are many source datasets with varied update processes, this issue template should be opened to track progress towards updating all source data

**All source data listed is to be uploaded as .csv files**

## Scraped by data library

- [x] bpl_libraries
      Source: Scraped from BPL website
      Source url: https://www.bklynlibrary.org/locations/json
- [x] nypl_libraries
      Source: Scrape from NYPL website
      Source url: https://www.nypl.org/locations/list
- [x] uscourts_courts
      Source: Court locator for NY state
      Source url: http://www.uscourts.gov/court-locator/city/New%20York/state/NY
- [x] dcp_colp
      Source: Bytes
      Source url: https://www1.nyc.gov/site/planning/data-maps/open-data.page#city_facilities
      Need to specify version when archiving the data (check on the website for date last updated).
- [x] nysoasas_programs
      Source: Scraped from OASAS website
      Source url: https://webapps.oasas.ny.gov/providerDirectory/index.cfm?search_type=2
      Need to set version to today’s date as DD-Mon-YY. Example: 13-Nov-20

## Source data from OpenData portals

To see if a dataset needs to be uploaded, check date last updated in open data/bytes against version in data library.

- [x] dca_operatingbusinesses https://data.cityofnewyork.us/Business/Legally-Operating-Businesses/w7w3-xahh
- [x] dcp_facilities_with_unmapped https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-selfac.page
- [x] dcla_culturalinstitutions https://data.cityofnewyork.us/Recreation/DCLA-Cultural-Organizations/u35m-9t32
- [x] dfta_contracts https://data.cityofnewyork.us/Social-Services/Department-for-the-Aging-NYC-Aging-All-Contracted-/cqc8-am9x
      NOTE: `providertype` column has two types of meal categories. One of them, **CITY MEALS ADMINISTRATIVE SERVICES CONTRACTS**, should only have one record (city meals). If there are more records in this category, need to revise code in `dfta_contracts.sql`.
- [x] doe_busroutesgarages https://data.cityofnewyork.us/Transportation/Routes/8yac-vygm

- [x] dot_pedplazas https://data.cityofnewyork.us/Transportation/Routes/k5k6-6jex

- [x] sca_enrollment_capacity https://data.cityofnewyork.us/Education/Enrollment-Capacity-And-Utilization-Reports-Target/8b9a-pywy
- [x] dohmh_daycare https://data.cityofnewyork.us/Health/DOHMH-Childcare-Center-Inspections/dsg6-ifza
- [x] dpr_parksproperties https://nycopendata.socrata.com/Recreation/Parks-Properties/enfh-gkve
      NOTE: DPR open data table URLs are not consistent. Be sure to double-check before running from the recipes app.
- [x] dsny_garages https://data.cityofnewyork.us/Environment/DSNY-Garages/xw3j-2yxf
- [x] dsny_specialwastedrop https://data.cityofnewyork.us/Environment/DSNY-Special-Waste-Drop-off-Sites/242c-ru4i
- [x] dsny_donatenycdirectory https://data.cityofnewyork.us/Environment/DSNY-DonateNYC-Directory/gkgs-za6m
- [x] dsny_leafdrop https://data.cityofnewyork.us/Environment/Leaf-Drop-Off-Locations-in-NYC/8i9k-4gi5
- [x] dsny_fooddrop https://data.cityofnewyork.us/Environment/Food-Scrap-Drop-Off-Locations-in-NYC/if26-z6xq
- [x] dsny_electronicsdrop https://data.cityofnewyork.us/Environment/Electronics-Drop-Off-Locations-in-NYC/wshr-5vic
- [x] fdny_firehouses https://data.cityofnewyork.us/Public-Safety/FDNY-Firehouse-Listing/hc8x-tcnd
- [x] hhc_hospitals https://data.cityofnewyork.us/Health/Health-and-Hospitals-Corporation-HHC-Facilities/f7b6-v6v3
- [x] hra_jobcenters https://data.cityofnewyork.us/Business/Directory-Of-Job-Centers/9d9t-bmk7
- [x] hra_medicaid https://data.cityofnewyork.us/City-Government/Medicaid-Offices/ibs4-k445
- [x] hra_snapcenters https://data.cityofnewyork.us/Social-Services/Directory-of-SNAP-Centers/tc6u-8rnp
- [x] moeo_socialservicesitelocations https://data.cityofnewyork.us/City-Government/Verified-Locations-for-NYC-City-Funded-Social-Serv/2bvn-ky2h
- [x] nycha_communitycenters https://data.cityofnewyork.us/Social-Services/Directory-of-NYCHA-Community-Facilities/crns-fw6u
- [x] nycha_policeservice https://data.cityofnewyork.us/Housing-Development/NYCHA-PSA-Police-Service-Areas-/72wx-vdjr
      NOTE: this data is shown as a map on the website.
- [x] nysdec_solidwaste https://data.ny.gov/Energy-Environment/Solid-Waste-Management-Facilities/2fni-raj8
- [x] nysdoh_healthfacilities https://health.data.ny.gov/Health/Health-Facility-General-Information/vn5v-hh5r
- [x] nysdoh_nursinghomes https://health.data.ny.gov/Health/Nursing-Home-Weekly-Bed-Census-Last-Submission/izta-vnpq
- [x] nysed_nonpublicenrollment http://www.p12.nysed.gov/irs/statistics/nonpublic/
- [x] nysomh_mentalhealth https://data.ny.gov/Human-Services/Local-Mental-Health-Programs/6nvr-tbv8
- [x] nysopwdd_providers https://data.ny.gov/Human-Services/Directory-of-Developmental-Disabilities-Service-Pr/ieqx-cqyk
- [x] nysparks_historicplaces https://data.ny.gov/Recreation/National-Register-of-Historic-Places/iisn-hnyv
- [x] nysparks_parks https://data.ny.gov/Recreation/State-Park-Facility-Points/9uuk-x7vh
- [x] qpl_libraries https://data.cityofnewyork.us/Education/Queens-Library-Branches/kh3d-xhq7
- [x] sbs_workforce1 https://data.cityofnewyork.us/dataset/Center-Service-Locations/6smc-7mk6
- [x] usdot_airports https://geodata.bts.gov/datasets/aviation-facilities/explore?location=50.755910%2C-117.686932%2C22.58&showTable=true
      Use data-library to extract and archive data. Note, data-library uses a different link to extract the data. This link is provided as a reference for last date updated.
- [x] usdot_ports https://data-usdot.opendata.arcgis.com/datasets/usdot::docks/about
- [x] nysdec_lands https://data.gis.ny.gov/datasets/84b4cce8a8974c31a1c5584540f3aaae_0/about
- [x] usnps_parks https://public-nps.opendata.arcgis.com/datasets/nps::nps-boundary-1/about

## Manually check data for updates

The source datasets don't currently provide an API or export option on their websites. The data engineering team initially created the datasets and continues to maintain them internally, relying on the information available on the websites. Also, the source data websites don't report date updated as neatly as the open datasets, have to look at data itself.

- [x] fbop_corrections https://www.bop.gov/locations/list.jsp
      When searching by state, there should be 5 NY prisons, 3 of which are in NYC (Brooklyn/New York)
- [x] nycdoc_corrections https://www1.nyc.gov/site/doc/about/facilities-locations.page
      Source: NYCDOC locations directory
- [x] nycourts_courts http://www.nycourts.gov/courts/nyc/criminal/generalinfo.shtml#BRONX_COUNTY
- [x] nysdoccs_corrections https://doccs.ny.gov/find-facility
      Hand check for 1 facility in queens, 1 facility in Manhattan, 0 in the other 3 boros. Only look at the correctional facility locations, not the offices.

## Manual download

**`TODO`**: see respective `dcpy/library/templates` for details

- [x] doe_lcgms https://data.cityofnewyork.us/Education/LCGMS-DOE-School-Information-Report/3bkj-34v2
- [x] foodbankny_foodbanks http://www.foodbanknyc.org/get-help/
- [x] nysed_activeinstitutions https://eservices.nysed.gov/sedreports/list?id=1

### Will receive via email or FTP

- [x] dot_bridgehouses
- [x] dot_ferryterminals
- [x] dot_mannedfacilities
- [x] dot_publicparking
- [x] doe_universalprek (https://maps.nyc.gov/prek/data/pka/pka.csv)

## Last step

- [x] dcp*pops
      Source: Download from POPs app, available on DCP Commons. Be sure to only take the public version.
      \_Be sure to do this source last, as the OpenData release of POPs needs to be in sync*

**Comment by damonmcc** [comment]
resolving ingest/dataloading issues

**Comment by damonmcc** [comment]
noting that https://github.com/NYCPlanning/data-engineering/issues/1290 has details on potential changes to source data related to archiving with ingest instead of library

**Comment by fvankrieken** [comment]
Emailed DOE about universal prek (and #1066) on 1/29

**Comment by fvankrieken** [comment]
All source data archived 3/7 (after colp being finished and archived 3/6), initial build running, to be shared w/ GIS Monday assuming no glaring data issues

**Comment by jackrosacker** [comment]
@fvankrieken - requesting your feedback/sign off on facdb metadata.

Relevant data dictionary and readme can be found [here](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/Metadata%20for%20review?csf=1&web=1&e=ooQSv3)

1. Confirming that there are no structural or process changes that need to be logged in this section of the readme:
![Image](https://github.com/user-attachments/assets/a4e1e9e1-48a0-46aa-8958-9b7804c471d0)
2. The data dictionary has a data sources tab, that includes dataset names, dates, and URLs:
![Image](https://github.com/user-attachments/assets/8823a999-68c1-4365-9502-37a76cdc1d06)
    - When comparing this list to the `source_data_versions.csv` file, it looks like we use a number of datasets to build facilities that are not listed in the data dictionary table. We are inclined to include these, but wanted to check to see if there was a reason to not add to the data dictionary. Relevant datasets:
      - dcp_facilities_with_unmapped
      - dcp_mappluto_wi
      - dcp_boroboundaries_wi
      - dcp_ct2010
      - dcp_ct2020
      - dcp_councildistricts
      - dcp_cdboundaries
      - dcp_nta2010
      - dcp_nta2020
      - dcp_policeprecincts
      - dcp_school_districts
    - We don't have a reasonable method to keep the URL column up to date. Requesting that you add the source URL if possible as a field in the `source_data_versions.csv`

This is a lot, so happy to talk if easier.

**Comment by jackrosacker** [comment]
Spoke separately about this. Decided to:
- Add all datasets to the readme that are included in the `source_versions.csv` but are currently missing from the readme, with the exception of the dcp_facilities_with_unmapped dataset as flagged by Finn
- Leave source URLs as-is. There will be some degree of inaccuracy, but the same as for all previous builds.
- Publish this version of Facilities
- Work to add source URL values to all datasets in the `source_versions.csv` for the next build

fyi @croswell81 @caseysmithpgh

**Comment by damonmcc** [comment]
distributed to Bytes. must distribute everywhere else

**Comment by damonmcc** [comment]
distributed to OpenData
