### ISSUE TITLE
Data flow for AE Zoning API

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#660]
## Project Description

Application Engineering and Data Engineering will build a way to update the database used by the new Zoning API.

## Outcomes

1. "dev", "staging", and "production" instances of the Zoning API database, Zoning API, and AE Zoning Map PoC are hosted in Digital Ocean, Heroku, and Netlify, respectively.
2. When a new version of PLUTO has been distributed by Data Engineering to a folder in Digital Ocean Spaces, AE can validate and transform it into the tables needed for the Zoning API database.
3. Application Engineering can trigger a workflow to update the staging API database.
4. An engineer or QA team member can QA the new data in the staging environment.
5. Once the new data are deemed ready to promote to production, a workflow can be triggered to update the production API database.

## Timing

Complete by end of March

---

## Tasks

- [x] make new repo [`ae-data-flow`](https://github.com/NYCPlanning/ae-data-flow)
- [x] NYCPlanning/ae-data-flow#1
- [x] NYCPlanning/data-engineering#677
- [x] NYCPlanning/ae-data-flow#3
- [x] NYCPlanning/ae-data-flow#6
- [x] NYCPlanning/ae-data-flow#2
- [x] NYCPlanning/ae-data-flow#4
- [x] NYCPlanning/ae-data-flow#28
- [x] deploy Zoning API DBs
- [x] NYCPlanning/ae-data-flow#13
- [x] NYCPlanning/ae-data-flow#34
- [x] NYCPlanning/ae-data-flow#29
- [ ] deploy Zoning API server
- [ ] deploy Zoning Map PoC

### Bonus tasks

- [x] NYCPlanning/ae-data-flow#36
- [ ] NYCPlanning/ae-data-flow#41
- [ ] NYCPlanning/ae-data-flow#42
- [ ] NYCPlanning/ae-data-flow#43
- ~improve testing data flow tables to align with API expectations~
- ~deprecate use of `psql` CLI~

## Design

We're now keeping the `ae-data-flow` [README](https://github.com/NYCPlanning/ae-data-flow?tab=readme-ov-file#design) up to date with the latest design approach.

### Diagram

![workflow_zoning_api_update](https://github.com/NYCPlanning/ae-data-flow/blob/main/diagrams/workflow_zoning_api_update.drawio.png?raw=true)

### Outline from 3/12

- source data
  - PLUTO
    - will have been QAd by GIS and will include Zoning Districts with it
  - from `edm-distributions/dcp_pluto`
    - DE will be pushing QA'd data to this ASAP, will manually put it there for now
  - csvs preferred because they're easy to copy into a database
- load
  - copy csvs into an AE database
- transform
  - validate source data here?
  - transform tables via SQL queries
- replace
  - replace tables that the API is pointing to
  - how?
    - create new tables
      - tax_lots_new
    - rename old and new tables
      - old first, new second

---

### Motivations

Relevant discussion in `ae-private` repo [here](https://github.com/NYCPlanning/ae-private/discussions/14#discussioncomment-8697441)

The backend of the Zoning API ([repo](https://github.com/NYCPlanning/ae-zoning-api)) is a Postgres database. The structures of the API tables are defined in that repo [here](https://github.com/NYCPlanning/ae-zoning-api/tree/db-admin/src/schema) in the folder `/src/schema`.

This API is used by the Zoning Map PoC ([repo](https://github.com/NYCPlanning/ae-zoning-map-poc)).

PLUTO and Zoning Tax Lots (ZTL) are the sources of the data in the API DB. These sources are updated monthly by Data Engineering. So some of the tables in API DB must be updated monthly.

### Notes

@TylerMatteo's `poetry-boilerplate` repo [here](https://github.com/TylerMatteo/poetry-boilerplate)

AE's `equity-tool` repo has an example [here](https://github.com/NYCPlanning/equity-tool/actions/runs/5245127817) of a github action using staging & production environments.

**Comment by damonmcc** [comment]
Data Engineering scripts that currently generate AE's normalized files [here](https://github.com/NYCPlanning/data-engineering/tree/main/products/pluto/pluto_build/ae_output_scripts)

**Comment by fvankrieken** [comment]
Actual logic to generate the outputs for AE are [here](https://github.com/NYCPlanning/data-engineering/blob/main/products/pluto/pluto_build/sql/export_ae_tables.sql). They're currently only run by a special gha triggered manually by us, building tables in a specific build schema and then exporting.

Given that it's currently most convenient for us to generate these tables in the context of a pluto build (given that they use zoning district data and pluto db table), we could do a couple things
1. actually build these tables during pluto build, then export (as in, the dumped tables are in the draft/publish folder with other pluto outputs, and these can be pushed directly when we publish/package/trigger AE etl). Could export as csv, could export subset of tables as pg_dump (not sql file, but --data-only compressed custom output that could be run using pg_restore). A bit tidier than a sql file and don't have to worry about type safety. I _think_ we could export a subset of tables as a single file this way too, but need to refresh my memory on pg_dumps
2. when we package, we build these tables. maybe a tad cleaner conceptually, but it means zoning data would need to get pulled in during packaging, which is maybe a bit less clean
3. keep pluto build as is, and AE etl would need to actually process pluto to generate normalized output for loading. They would also need to pull in zoning data separately. Maybe a nice exercise to get them digesting our data and reading data from edm-recipes. But all of that is maybe adding unnecessary complexity right now.

I'm assuming we're thinking something along the lines of 1, right?

**Comment by damonmcc** [comment]
per meeting today, we're going with option 3

> keep pluto build as is, and AE etl would need to actually process pluto to generate normalized output for loading. They would also need to pull in zoning data separately. Maybe a nice exercise to get them digesting our data and reading data from edm-recipes. But all of that is maybe adding unnecessary complexity right now.

**Comment by damonmcc** [comment]
our first project outcome is

> "dev", "staging", and "production" instances of the Zoning API database, Zoning API, and AE Zoning Map PoC are hosted in Digital Ocean, Heroku, and Netlify, respectively.

Instances of the Zoning API database are now hosted in Digital Ocean.

But deploying remote instances of the API and PoC seem unlikely to be accomplished by this project. Barriers seems to be AE deciding on:
- deployment strategies (dev, staging, and prod environments)
- how/whether to containerize the API and PoC codebase (currently run locally via `npm [command]`
- hosting approaches (Heroku and Netlify on Digital Ocean were mentioned but there seems to be hesitation to not use Azure)

**Comment by damonmcc** [comment]
## next steps
- deploy API and PoC on Heroku and Netlify
- do most impactful bonus tasks

**Comment by fvankrieken** [comment]
Just noting that `pg_dump --data-only` does use a copy command under the hood

**Comment by damonmcc** [comment]
Closing out this project!

All 'bonus tasks" have been converted into [issue](https://github.com/NYCPlanning/ae-data-flow/issues) in the `ae-data-flow` repo.

AE's new Data Flow workflow works with the current state of the Zoning API and Zoning Map PoC. Those two downstream consumers of data are currently developed and deployed locally.

Deploying remote instances of them are significant tasks that are related to but no longer requirements of this work being considered complete.
