### ISSUE TITLE
Capital Projects Map

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#733]
## Deliverables

ESRI app: https://experience.arcgis.com/experience/150ca77c6dff4b079b7e079764121afe
AE staging app: https://staging-capitalplanning.nycplanningdigital.com/

<details><summary><h2>Project summary</h2></summary>
<p>

## Problems

DCP Borough offices, City Council staff, and City Hall staff can't find information about capital projects in their geographic areas of interest.

These groups often ask DCP's Capital Planning team to generate lists of capital projects filtered by certain geographic boundaries. The [Capital Projects Database](https://github.com/NYCPlanning/data-engineering/wiki/Product:-CPDB) (CPDB) is the source of that data.

Fulfilling these requests is repetitive and time-consuming because these lists of filtered projects aren’t pre-computed and there are no workflows or application with this filtering feature.

Fulfilling these requests occupies DCP resources and limited access to this data impedes informed decision-making by DCP and other groups.

DCP Executive has made this problem a high priority and has requested solutions by the end of 2024 Q2.

## Goals

We will make it easier to know which capital projects are located in a geographic boundary. The boundaries of interest are Community Districts and City Council Districts.

People want to see capital projects in an interactive map, filter them by a geographic boundary, and download a CSV file with the details of projects.

</p>
</details>

---

## Objectives

1. CPDB includes which Community District and City Council District each capital project intersects with.
2. CPDB is presented in an application built using ArcGIS Experience Builder.
3. CPDB is presented in an application built using Application Engineering's new tech stack.
4. Any application built has the following features:
    1. has a map showing capital projects
    2. can filter by Community District or City Council District
    3. can download filtered data as a CSV file
    4. uses the latest release of CPDB

### ESRI app
- Intended users: NYC agencies
- Available to the public by 6/28
- Will not promote publicly, but public access will be impactful

### Custom app
- Intended users: everyone
- Staging version available to DCP by 6/28
- One month for DCP testing and completion of all features
- Available to the public by 7/28
- Will be promoted publicly

## Measures of success

1. Number of requests for filtered capital projects (decrease)
2. Time spent by Capital Planning fulfilling requests for filtered capital projects  (decrease)
3. Time between a CPDB release and data updates in new apps  (decrease)
4. Visits to new apps
5. Downloads of data from new apps

## [Roadmap](https://github.com/orgs/NYCPlanning/projects/47/views/1)

---

## Tasks

- [x] NYCPlanning/data-engineering#764
- [x] NYCPlanning/data-engineering#779
- [x] NYCPlanning/data-engineering#782
- [x] #884
- [x] NYCPlanning/data-engineering#783
- [x] NYCPlanning/edm-overview#1037
- [x] NYCPlanning/data-engineering#784

## Discussions

https://github.com/NYCPlanning/ae-private/discussions/23
https://github.com/NYCPlanning/ae-cp-map/discussions/4
https://github.com/NYCPlanning/ae-private/discussions/27
https://github.com/NYCPlanning/ae-private/discussions/22

---

## Project team

**Capital Planning**: Describes user needs and gives feedback on applications.

**Product Management**: Does user research, drafts wireframe designs, and gives feedback on applications.

**Data Engineering** (DE): Modifies and builds CPDB.

**GIS**: Builds an ArcGIS Experience Builder application.

**Application Engineering** (AE): Builds a new API and custom application.

Project Lead: Damon McCullough / Project Sponsors: David Parish, Amanda Doyle

## Communication

We use github and a new Microsoft Teams channel called [Capital Projects Map](https://teams.microsoft.com/l/channel/19%3A4ddcd4dfdb6144e6a14cc51280737bb0%40thread.skype/Capital%20Projects%20Map?groupId=ce454ad8-a936-456b-8926-c9157c03db79&tenantId=) for group communications.

Bi-weekly updates are shared with Project Sponsons on Friday afternoons in the teams channel.

After the first month, we'll do bi-weekly (maybe weekly) demos on Friday afternoons for the Project Sponsors and any interested Project Team members.

---

## Resources

[Capital Projects Database wiki](https://github.com/NYCPlanning/data-engineering/wiki/Product:-CPDB) (CPDB)

CPDB on [Bytes](https://www.nyc.gov/site/planning/data-maps/open-data/dwn-capital-planning-database.page) and on [Open Data](https://data.cityofnewyork.us/browse?q=capital%20projects%20database&sortBy=relevance)

[Capital Planning Explorer](https://capitalplanning.nyc.gov/map#10/40.7128/-74.0807) (CPE)
[Capital Projects Dashboard](https://www.nyc.gov/site/operations/performance/capital-projects-dashboard.page) by MOO

[Slides: Capital Planning 101](https://nyco365.sharepoint.com/:p:/s/NYCPLANNING/cp/EbgSjxZnsC1Ii2PhJRPtZUEBITCiGWnVMWcRiJAmUwe2rQ?CID=b5548df2-ab57-fe02-65ec-9ee53a68f1cc&clickParams=eyJYLUFwcE5hbWUiOiJNaWNyb3NvZnQgT3V0bG9vayBXZWIgQXBwIiwiWC1BcHBWZXJzaW9uIjoiMjAyNDA1MzEwMDYuMTAiLCJPUyI6Ik1hYyBPUyBYIHVuZGVmaW5lZCJ9)
[Slides: Capital Planning Explorer, NYC Open Data Week, March 2022](https://documentcloud.adobe.com/spodintegration/index.html?locale=en-us)

[Understanding the Budget: A Guide to the Capital Budget](https://www.ibo.nyc.ny.us/iboreports/IBOCBG.pdf)

**Comment by mbh329** [comment]
@damonmcc Timing sounds good to me but want to flag that the user outreach process will probably push the start date back. Guess it all depends a bit on AE and how much user input they would be looking for.

As far as the wording, I'd add that having a borough filter would be helpful. I can work with everyone on the final wording of the website but as far as the project statement goes I think that looks good

**Comment by damonmcc** [comment]
@mbh329
Gotcha. I think we can safely start on MVPs of the apps and apply any significant new user input when it comes in.

I've now added Borough to the list of "geographic areas of interest"! Should be easy enough and I can imagine it'd seem odd if we _didnt't_ have it.

**Comment by TylerMatteo** [comment]
@damonmcc @AmandaDoyle Do we think we could sell leadership on the end of June for delivery of the custom app? Not counting this week, June 1st is only 3 and half sprints away. I'm not confident my team could deliver that alongside all of the other projects we have (PFF/Zola/ZAP Search improvements, etc).

> I've now added Borough to the list of "geographic areas of interest"! Should be easy enough and I can imagine it'd seem odd if we didnt't have it.

Agree this is relatively easy and might be odd not to have, but if we're talking about delivery dates, we should really settle on what is/isn't included in the first version we're building towards ASAP.

**Comment by TylerMatteo** [comment]
How about we just focus on Community Districts and City Council Districts for now? If there's time, we can work on boroughs as well.

Another question for the group - how would we feel about only including mapped projects in the first version? It sounds like the focus for users is viewing projects relevant to a particular geographic boundary, so unmapped projects may not be as relevant and including them introduces some tricky UI/UX questions that we would have to account for.

**Comment by jpiacentinidcp** [comment]
As for user research and what information it can provide us, I am in process of setting up conversations with relevant stakeholders that David P connected me to. However, I am in agreement with the rest of the team that we have enough baseline scope to begin work while user research is in progress.

These conversations should happen shortly after our kickoff so I can integrate any relevant findings as early as possible, with the understanding that our timeline prohibits significant additional scope. This research ideally helps clarify specific UI/UX aspects of current in-scope functionality.

**Comment by damonmcc** [comment]
@TylerMatteo @croswell81 @jpiacentinidcp 

I've drafted a problem statement and some measures of success and added them this project issue. They're at the top in a collapsible section called `Project summary`. Let me know here if you have any suggestions for edits!

Putting it first seemed good so that it's hard to miss. A collapsible section seemed good since this is a lot of (important) background text but when people are working on the project they probably shouldn't have to scroll through it every time to get to the sections they're more likely to be looking for (like when you just want the recipe but there's a novel before it).

**Comment by TylerMatteo** [comment]
@damonmcc just my two cents on the problem and measures of success:

For a problem statement, I think something like "City council staff can't find information about capital projects in their area" is more "user focused". The burden on DCP staff is definitely important and relevant to how we measure success, but it's not the actual problem, in my opinion.


* Requested data is accessible to the public
* Requested apps are accessible to the public
* Decrease in requests for filtered capital projects
* Decrease in time spent by Capital Planning fulfilling requests for filtered capital projects

3 and 4 sounds great to me. 1 and 2 are good but is there a way we could focus them more on outcomes? We could make an app that doesn't actually meets anyone's needs and still satisfy "Requested apps are accessible to the public". We could track how much the data are downloaded or how much the site is visited.

**Comment by damonmcc** [comment]
@TylerMatteo good ideas! I've added to the project statement and the measures of success

hard to say how many visits = success, but we can get more specific with the measure later. maybe comparing visits to similar sites?

**Comment by TylerMatteo** [comment]
Yeah, site visits are, at best, a stop gap until we identify better metrics. There are plenty of scenarios where folks having to revisit the site or spend increased amounts of time on the site are actually indicative of a _worse_ experience. @jpiacentinidcp outreach and research with external users should help us identify what user are actually trying to accomplish with this data, which in turn should help us identify better metrics.

**Comment by mbh329** [comment]
@jpiacentinidcp were you able to set up any meetings with users for the user research component of the project? Or are we moving forward without the input from the IBO and BK Downtown Partnership?

**Comment by damonmcc** [comment]
taking this out of DE github project now that the majority of project planning/work is done. remaining work is now managed in the AE github project [here](https://github.com/orgs/NYCPlanning/projects/35)
