### ISSUE TITLE
draft designs for Capital Projects apps

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#783]
github discussion [here](https://github.com/NYCPlanning/ae-private/discussions/23)

### CPDB columns to highlight

CPDB column | Field name in app
-- | --
magenname | Managing Agency
adtotal | Total Budget
pctotal | Committed FY of Budget
altotal | Allocated FY of Budget
cototal | Committed to Date
sptotal | Spend to Date
mindate | Min Commitment Date
maxdate | Max Commitment Date

---

## tasks
- [x] hi-fi mobile wireframes
- [x] by 5/8: lo-fi desktop wireframes and describe to AE how desktop app should work
- [x] share wireframes with Capital Planning team
- [x] map CPDB fields to app elements and provide documentation to AE
- [x] draft examples of copy in significant app elements
- [x] work on cartography/map design
- [x] highlight significant fields in project card/list
- [x] draft language for Welcome pages (same-ish for both apps)

**Comment by jpiacentinidcp** [comment]
@mbh329 Thanks for chatting today. Adding the draft text to this comment for now:

### **Welcome to the Capital Projects Portal**

**Capital Projects Database**

The Capital Projects Database includes information on New York City’s potential, planned, and ongoing capital projects. To better help you understand New York City’s capital project portfolio within and across major agencies, we have organized  mapped projects in this portal. Unmapped projects, such as the purchase of vehicles or digital infrastructure, are not included in this tool.

**How to Use This Tool**

Select a project on the map to learn more about the relevant agencies and capital commitments, or filter by specific geographies to see all projects in that area. You can also export your selection as a CSV table or ESRI Shapefile.

**More Information**

To learn more about the Capital Projects Database and how New York City invests in building a better future, go to {......}. If you would like to download the complete database, including unmapped projects, you can find that here:

**Comment by jpiacentinidcp** [comment]
### **FIGMA LINKS**

[Mail Folder](https://www.figma.com/files/project/61530894?fuid=1059913896950298535
)

[Design File](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=0-1&t=rKJZxStVchQuVmVe-0)

[Routes](https://www.figma.com/design/3FqgaQqGEhzhqLaeDrK45t/Routes?m=auto&t=dKHeajnWwMoWR9Q0-6)

**Comment by mbh329** [comment]
I will start taking a look today, thanks for the reference point.

**Comment by damonmcc** [comment]
hey @mbh329. don't wanna drive you nuts with too many issues. since the work is so similar and should probably align, I thought it'd be helpful to reply to [your ESRI app question](https://github.com/NYCPlanning/edm-overview/issues/1037#issuecomment-2145883424) here

> What do you mean by "pop up and text designs"?

similar to the above "which CPDB fields (especially new ones) should be highlighted in the app", we'd love to know which fields should be highlighted in the ESRI app. below is a screenshot of the popups related to a single project

<img width="1052" alt="Screenshot 2024-06-03 at 5 20 09 PM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/bf4f825f-0e83-493e-af1d-56634e681667">

and sorry "text design" is very vague. The ESRI app has lots of places where custom introductory or instructional text can be placed.

if you have any suggestions or opinions in that text, happy to work them in. if not, we can do a first pass and get your feedback. we'll likely try to align with the draft text in the designs for the Custom app

**Comment by caseysmithpgh** [comment]
Hey @mbh329, pinging you in reference to @damonmcc's previous message. 
I plan to tackle the next ESRI app iterations in the second half of this week, but before I do so it would be helpful to get you input on pop-ups and important fields to highlight/group together.

**Comment by damonmcc** [comment]
hey @caseysmithpgh. Max and I reviewed CPDB fields and picked the faves. this issue description now has the list

for those $ related fields, the order they're in is important since it reflects the sequence of funding for a capital project

since these are the same fields we'll want to highlight in the custom app, I'll work on getting these into the relevant figma design mockups/whatever form will be most helpful for them

**Comment by caseysmithpgh** [comment]
#### Implemented some changes found in the design fellows feedback [here](https://www.figma.com/board/VYfTbsgEbeQG3lnLRrvrp6/ESRI-Design-Comments?node-id=0-1&t=bIoKRFEa3EIxT1al-0) (See Damon for access)

Home page: 
1. Left aligned text
2. Increased font size across multiple sections; reduced negative space
3. Corrected difference between CC/CD buttons when hovering
4. Clarified "Geography Selector"
5. Added tool tips to describe different geographies; pulled directly from ESRI metadata

Instant Apps
1. Reverted selection highlight to no fill, default ESRI outline (00ffff)
2. Removed select by polygon options on lefthand menu
3. Configured legend to open on initial load

There was a lot of great feedback that was not able to be implemented due to ESRIs limitations within the out of the box tooling. Perhaps our wonderful design fellows ought to target ESRI next for their next gig!
