### ISSUE TITLE
Opendata: Packaging - Data Dictionary / README generation from metadata

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#944]
### Tasks

These are the bare minimum things to do before potentially handing off to fellows:

- [ ] Research what we need from OTI to meet compliance
- [ ] List common elements in our READMEs and Data Dictionarys. (e.g. tables, images?, etc.)
- [ ] Find DCP style guide, or reference examples? Maybe AE has something?
- [ ] Find a few reference examples that we like, from out in the wide world
- [ ] Research the technical side of things (e.g. generating pdfs)

**Comment by alexrichey** [comment]
Running comment...

### Common README/DD elements

#### Changelog
- should point at the Github tag/release?

**Comment by damonmcc** [comment]
for reviewing the current state of our metadata out in the world, I added links to the [Data Catalog](https://github.com/NYCPlanning/data-engineering/wiki/Data-Catalog) in the DE wiki for each data product's destinations

on NYC Open Data, we usually have a data dictionary excel file. on DCP Bytes, we usually have a data dictionary and a readme PDF (this is a generalization of what we have at both destinations)

**Comment by damonmcc** [comment]
I think the only example of a templated markdown file we have is for CEQR: [data-engineering/products/ceqr/recipes/dep_cats_permits/README.md](https://github.com/NYCPlanning/data-engineering/blob/main/products/ceqr/recipes/dep_cats_permits/README.md)

**Comment by alexrichey** [comment]
@damonmcc also, here's the [AE Tokens/Typography](https://streetscape.nycplanningdigital.com/?path=/docs/tokens-typography--docs) that Tyler mentioned two weeks'ish ago
